[package]
name = "nft-stake-contract-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.nft-stake-contract]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.8"
